### ISSUE TITLE
fails on ubuntu 16.04

### ISSUE THREAD

**Issue by hedii** [geerlingguy/ansible-role-mysql#112] opened 2016-04-27 12:29 UTC
Hi,
i made a box with your repo packer-ubuntu-1604.
have the latest release of geerlingguy/ansible-role-mysql.
i have having the exact same issue as #63 that is supposed to be resolved in #108 

````
PLAY [Install db servers] ******************************************************

TASK [setup] *******************************************************************
ok: [10.0.0.13]

TASK [geerlingguy.mysql : Include OS-specific variables.] **********************
ok: [10.0.0.13]

TASK [geerlingguy.mysql : Define mysql_packages.] ******************************
ok: [10.0.0.13]

TASK [geerlingguy.mysql : Define mysql_daemon.] ********************************
ok: [10.0.0.13]

TASK [geerlingguy.mysql : Define mysql_slow_query_log_file.] *******************
skipping: [10.0.0.13]

TASK [geerlingguy.mysql : include] *********************************************
skipping: [10.0.0.13]

TASK [geerlingguy.mysql : include] *********************************************
included: /Users/hedichaibi/Desktop/boxes/ansible/roles/geerlingguy.mysql/tasks/setup-Debian.yml for 10.0.0.13

TASK [geerlingguy.mysql : Check if MySQL is already installed.] ****************
ok: [10.0.0.13]

TASK [geerlingguy.mysql : Update apt cache if MySQL is not yet installed.] *****
ok: [10.0.0.13]

TASK [geerlingguy.mysql : Ensure MySQL Python libraries are installed.] ********
changed: [10.0.0.13]

TASK [geerlingguy.mysql : Ensure MySQL packages are installed.] ****************
changed: [10.0.0.13] => (item=[u'mysql-common', u'mysql-server'])

TASK [geerlingguy.mysql : Ensure MySQL is stopped after initial install.] ******
changed: [10.0.0.13]

TASK [geerlingguy.mysql : Delete innodb log files created by apt package after initial install.] ***
changed: [10.0.0.13]
 [WARNING]: Consider using file module with state=absent rather than running rm


TASK [geerlingguy.mysql : Check if MySQL packages were installed.] *************
ok: [10.0.0.13]

TASK [geerlingguy.mysql : include] *********************************************
included: /Users/hedichaibi/Desktop/boxes/ansible/roles/geerlingguy.mysql/tasks/configure.yml for 10.0.0.13

TASK [geerlingguy.mysql : Copy my.cnf global MySQL configuration.] *************
changed: [10.0.0.13]

TASK [geerlingguy.mysql : Verify mysql include directory exists.] **************
skipping: [10.0.0.13]

TASK [geerlingguy.mysql : Copy my.cnf override files into include directory.] **

TASK [geerlingguy.mysql : Create slow query log file (if configured).] *********
skipping: [10.0.0.13]

TASK [geerlingguy.mysql : Set ownership on slow query log file (if configured).] ***
skipping: [10.0.0.13]

TASK [geerlingguy.mysql : Create error log file (if configured).] **************
changed: [10.0.0.13]
 [WARNING]: Consider using file module with state=touch rather than running touch


TASK [geerlingguy.mysql : Set ownership on error log file (if configured).] ****
skipping: [10.0.0.13]

TASK [geerlingguy.mysql : Ensure MySQL is started and enabled on boot.] ********
fatal: [10.0.0.13]: FAILED! => {"changed": false, "failed": true, "msg": "Job for mysql.service failed because the control process exited with error code. See \"systemctl status mysql.service\" and \"journalctl -xe\" for details.\n"}

````

my vars:

````
mysql_root_password_update: yes
mysql_root_password: "mypassword"
mysql_databases:
# 2 databases...
mysql_users:
# 2 users...
````

**Comment by jonpugh** [comment] 2016-04-28 16:37
I believe I fixed this in my recent PR: https://github.com/geerlingguy/ansible-role-mysql/pull/115

**Comment by jonpugh** [comment] 2016-04-28 16:41
The cause is that the step below is skipped because it is using an incorrect variable.

```
TASK [geerlingguy.mysql : Set ownership on error log file (if configured).] ****
skipping: [10.0.0.13]
```

**Comment by geerlingguy** [comment] 2016-04-30 00:27
This should now be fixed in the latest version of the role. Note that I don't yet have automated tests running for 16.04 (had to work through some Docker/pip issues initially), but I've tested everything locally and in Drupal VM and it seems to be working fine.

Follow https://github.com/geerlingguy/ansible-role-mysql/pull/110 for updates on the Ubuntu 16.04 automated tests.

**Closed by geerlingguy** 2016-04-30 00:27 UTC

**Comment by alfonsomga** [comment] 2016-08-13 04:12
I'm using vm box ``geerlingguy/ubuntu1404`` and I'm stuck at the same error.

Any solution? 
What vm box should I use to avoid this error?

**Comment by alfonsomga** [comment] 2016-08-13 15:08
I tried to run it on a DigitalOcean droplet using ``Ubuntu 14.04.5 x64`` distribution but same error is appearing:

```
TASK [geerlingguy.mysql : Ensure MySQL is started and enabled on boot.] ********
task path: /Users/Alfonso/Desktop/Projects/V1/panel-env/ansible/roles/geerlingguy.mysql/tasks/configure.yml:67
<178.62.55.199> ESTABLISH SSH CONNECTION FOR USER: root
<178.62.55.199> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/Users/Alfonso/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/Alfonso/.ansible/cp/ansible-ssh-%h-%p-%r 178.62.55.199 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1471100498.12-225006982974948 `" && echo ansible-tmp-1471100498.12-225006982974948="` echo $HOME/.ansible/tmp/ansible-tmp-1471100498.12-225006982974948 `" ) && sleep 0'"'"''
<178.62.55.199> PUT /var/folders/wq/p9yn03qs5p16fq115w2qzk980000gn/T/tmpVuj3s5 TO /root/.ansible/tmp/ansible-tmp-1471100498.12-225006982974948/service
<178.62.55.199> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/Users/Alfonso/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/Alfonso/.ansible/cp/ansible-ssh-%h-%p-%r '[178.62.55.199]'
<178.62.55.199> ESTABLISH SSH CONNECTION FOR USER: root
<178.62.55.199> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/Users/Alfonso/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/Users/Alfonso/.ansible/cp/ansible-ssh-%h-%p-%r -tt 178.62.55.199 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1471100498.12-225006982974948/service; rm -rf "/root/.ansible/tmp/ansible-tmp-1471100498.12-225006982974948/" > /dev/null 2>&1 && sleep 0'"'"''
fatal: [178.62.55.199]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"arguments": "", "enabled": true, "name": "mysql", "pattern": null, "runlevel": "default", "sleep": null, "state": "started"}, "module_name": "service"}, "msg": "start: Job failed to start\n"}

```
