### ISSUE TITLE
user password generated by role is not been hashed correctly into the user table 

### ISSUE THREAD

**Issue by mnothic** [geerlingguy/ansible-role-mysql#37] opened 2015-05-29 20:13 UTC
when create user with role can't authenticate into the mysql, y tested too many times and then put the same password by hand with sql update and the password hash is different.
other issue is the mysql_root_password works fine but the mysql_user not. I explain:

```yaml
mysql_root_password: 'secret'
```

generate this:

```
| root             | *3B375FF2470854FD02220F5F0D8FB3B7DD3E7B0E | localhost |
```

but this:

```yaml
mysql_users:
  - name: sast
    host: '%'
    password: 'secret'
    priv: '*.*:ALL'
```

generate this:

```
| sast             | *196BDEDE2AE4F84CA44C47D54D78478C7E2BD7B7 | %         |
```

and connect in the localhost and update this:

```
mysql> set password for 'sast'@'%'=PASSWORD('secret');
Query OK, 0 rows affected (0.01 sec)
mysql> select user,password,host from mysql.user where user = 'sast';
+------+-------------------------------------------+------+
| user | password                                  | host |
+------+-------------------------------------------+------+
| sast | *3B375FF2470854FD02220F5F0D8FB3B7DD3E7B0E | %    |
+------+-------------------------------------------+------+
1 row in set (0.00 sec)
```

then I think the problem is in mysql_users items but not in mysql_root_password process

**Comment by mnothic** [comment] 2015-06-04 14:43
I have to do this workaround:

# file: mysql/tasks/users.yml

- name: MySQL | Make sure the MySQL users are present
  mysql_user:
    name: "{{item.name}}"
    password: "{{item.pass | default('pass')}}"
    priv: "{{item.priv | default('*.*:ALL')}}"
    state: present
    host: "{{item.host | default('localhost')}}"
  with_items: mysql_users
  when: mysql_users|length > 0

- name: Reset remote users password (this is a workaround)
  shell: echo "UPDATE mysql.user SET password=PASSWORD('{{ mysql_root_password }}') WHERE host='%';" | mysql

- name: restart mysql (because handler don't work)
  shell: service mysql restart

- name: Show hash password to compare
  shell: echo "SELECT user, password FROM mysql.user WHERE host='%';" |mysql

**Comment by geerlingguy** [comment] 2015-06-27 02:52
@mnothic - [Drupal VM](http://www.drupalvm.com/) uses a custom user/password to connect to MySQL locally, and I just tested on fresh CentOS 6, Ubuntu 12.04, and Ubuntu 14.04 VMs with this role and the following playbook:

```yaml
---
- hosts: all
  sudo: yes

  vars:
    mysql_users:
      - name: geerling
        host: '%'
        password: 'secret'
        priv: '*.*:ALL'

  roles:
    - geerlingguy.mysql
```

I was able to connect within the VM using `mysql -u geerling -p` then entering the password. I tried a couple different combinations as well, and it had no issue.

I wonder if maybe the version of Ansible you're using is having trouble setting the password. I've been pinned to Ansible 1.9.0.1 since there are a couple other strange MySQL bugs with Ansible's MySQL module in 1.9.1 (which I believe are fixed in 1.9.2).

If you're still having this issue, can you please post what OS you're running, what version of MySQL you're running (`mysql --version`), and what version of Ansible you're running on the host (`ansible --version`)?

**Comment by mnothic** [comment] 2015-06-28 10:40
Use ansible 1.9.1 os used is Ubuntu 14.04.2 LT and mysql  Ver 14.14 Distrib 5.5.43, for debian-linux-gnu (x86_64) using readline 6.
and this is not a drupalvm is a fresh install from 'ubuntu/trusty64' with vagrant

**Comment by geerlingguy** [comment] 2015-06-28 21:55
@mnothic - Can you try installing Ansible 1.9.0.1 instead to see if that fixes the issue? I have a feeling that this issue (and a few others that are cropping up) are related to some changes made in Ansible 1.9.1 and/or 1.9.2.

If you used pip to install Ansible, you can run:

```
sudo pip uninstall ansible
sudo pip install ansible==1.9.0.1
```

Then run the playbook again and see if the hashes/passwords are correct.

**Comment by geerlingguy** [comment] 2015-06-29 03:13
I'm still unable to reproduce when running Ansible 1.9.2 on Mac OS X to install on either Ubuntu 12/14, or CentOS 6/7... The only time I had any strange issues was when running 1.9.1 :(

**Closed by geerlingguy** 2015-06-29 03:13 UTC
Labels: question

**Comment by mnothic** [comment] 2015-06-29 07:41
OK Thanks I will upgrade it ASAP to test it.
